### ISSUE TITLE
Role fails on systems with systemd-timesyncd as a separate package

### ISSUE THREAD

**Issue by vrusinov** [stuvusIT/systemd-timesyncd#14]
Some systems (e.g. RHEL and its derivatives such as CentOS) have a separate package `systemd-timesyncd` which needs to be installed before attempting to enable and start the service.

**Comment by neumantm** [comment]
Yes this is correct.
That package would need to be installed by another role.
This was initially done to support as many distros as possible.

However, debian (the distro we use most) has now also switched to it being a seperate package.
Therefore, #16 adds the task to install the package via apt.

I'm afraid this will not help RHEL or CentOS users, though.
