### ISSUE TITLE
Use official Ansible timezone module to configure timezone

### ISSUE THREAD

**Issue by Atem18** [stuvusIT/systemd-timesyncd#4]
Hi, instead of coding the logic to configure timezone, it's better to use the default module of Ansible : https://docs.ansible.com/ansible/latest/modules/timezone_module.html

**Comment by Atem18** [comment]
@dasJ I made a pull request :)

**Comment by dasJ** [comment]
Thank you!

**Comment by Atem18** [comment]
Np !
