### ISSUE TITLE
Please add a tag

### ISSUE THREAD

**Issue by gmangin** [stuvusIT/systemd-timesyncd#8]
Hello :) 

could you please add tags on your code ?
thanks a lot ! it working great !

**Comment by SlothOfAnarchy** [comment]
Hi gmangin, if you open a PR adding the tags, I will review and merge it.
You could also add the tag in your local playbook when including the role, that's how we do it in our organization.

**Comment by gmangin** [comment]
thanks for the feedback, i will see how to add the tag in my local playbook
